# Generated by Django 5.2 on 2025-04-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(max_length=122)),
                ('areacode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
